version: "3.8"
services:
  strapi:
    container_name: strapi
    build: .
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    ports:
      - 1337:1337
    volumes:
      - strapi_data:/var/lib/mysql
      - public:/app/public/uploads
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
    depends_on:
      - strapiDB
    networks:
      - croissants

  strapiDB:
    image: mysql
    container_name: strapi_db
    volumes:
      - strapi_data:/var/lib/mysql
      - public:/app/public/uploads
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${DATABASE_USERNAME}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - 3307:3306
    networks:
      - croissants

volumes:
  strapi_data:
  public:

networks:
  croissants:
    external:
      name: croissants